# Generated by Django 3.2.4 on 2022-01-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dynamic_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic_product',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
