# Generated by Django 3.2.4 on 2022-02-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
